Website/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^$','blog.views.index'),
    url(r'^page/(?P<page>\d+)/$', 'blog.views.index'),
    url(r'^entry/(?P<entry_id>\d+)/$', 'blog.views.read'),
    url(r'^write/$', 'blog.views.write_form'),
    url(r'^add/post/$', 'blog.views.add_post'),
    url(r'^add/comment/$', 'blog.views.add_comment'),
    url(r'^add/user/$', 'blog.views.add_user'),
    url(r'^get_comments/(?P<entry_id>\d+)/$', 'blog.views.get_comments'),
    url(r'^login/$', 'blog.views.login_user'),
    url(r'^logout/$', 'blog.views.logout_user'), 
    url(r'^sign_up/$', 'blog.views.sign_up'),
    url(r'^delete/post/(?P<entry_id>\d+)/$','blog.views.delete_post'),
    url(r'^update/post/(?P<entry_id>\d+)/$','blog.views.update_post'), 
    url(r'^update/post/complete/','blog.views.update_post_complete'),

    url(r'^reset/password_form/$', 'django.contrib.auth.views.password_reset', 
        {'template_name': 'reset_password/reset_password_form.html',
	'post_reset_redirect' : '/reset/password_sent'}, name='password_reset'),

    url(r'^reset/password_sent/$','django.contrib.auth.views.password_reset_done',
	{'template_name':'reset_password/reset_password_sent.html'},name='password_reset_sent'),

    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>.+)/$',
	'django.contrib.auth.views.password_reset_confirm',
	{'template_name':'reset_password/reset_password_confirm.html'},name='password_reset_confirm'),

    url(r'^rest/password_complete/$', 
        'django.contrib.auth.views.password_reset_complete',
	{'template_name':'reset_password/reset_password_complete.html'},name='password_reset_complete'),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
# -*- coding: utf-8 -*-
from django.db import models
from django.conf import settings


class Categories(models.Model):
    Title = models.CharField(max_length=40, null=False)
    def __unicode__(self):
        return self.Title
	
class TagModel(models.Model):
    Title = models.CharField(max_length=20, null=False)
    def __unicode__(self):
        return self.Title

class Entries(models.Model):
    User = models.ForeignKey(settings.AUTH_USER_MODEL)
    Title = models.CharField(max_length=80, null=False)
    Content = models.TextField(null=False)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)    
    Category = models.ForeignKey(Categories)
    Tags = models.ManyToManyField(TagModel)
    Comments = models.PositiveSmallIntegerField(default=0, null=True)
    Image = models.ImageField(upload_to = 'uploaded', null=True)
    def delete(self, *args, **kwargs):
        self.Image.delete()
        super(Entries, self).delete(*args, **kwargs)
    def __unicode__(self):
        return self.Title

class Comments(models.Model):
    User = models.ForeignKey(settings.AUTH_USER_MODEL)
    Content = models.TextField(max_length=2000, null=False)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)    
    Entry = models.ForeignKey(Entries)

blog/forms.py
# -*- coding: utf-8 -*-
from django import forms

class ImageUploadForm(forms.Form):
    image = forms.ImageField()

blog/views.py
# -*- coding: utf-8 -*-
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render,redirect, get_object_or_404
from django.forms import ModelForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User
from blog.forms import ImageUploadForm
from blog.models import *
import md5

def delete_post (request, entry_id=None):
    try:
    	entry = get_object_or_404(Entries, id=int(entry_id))    
    except:
        return HttpResponse('Post does not exist anymore')
    if request.method=='POST':
        entry.delete()
        return HttpResponseRedirect('/')
    return render(request, 'delete_post_form.html', {'object':entry})

def update_post(request, entry_id=None):
    try:
    	entry = get_object_or_404(Entries, id=int(entry_id))    
    except:  
        return HttpResponse('Post does not exist anymore')
    
    categories = Categories.objects.all()
    context={
        'categories':categories,
	'current_entry':entry,
    }
    return render(request, 'update_post_form.html', context)

def update_post_complete(request):    
    try:
    	entry = Entries.objects.get(id=request.POST['entry_id'])    
    except:  
        return HttpResponse('Post does not exist anymore %s' %request.POST['entry_id'])
    edit_title = request.POST['title']
    edit_content = request.POST['content']
    edit_category = Categories.objects.get(id=request.POST['category'])

    # 글 꼬리표 처리    
    if request.POST.has_key('tags') == True:
        tags = map(lambda str: str.strip(), unicode(request.POST['tags']).split(','))
        tag_list = map(lambda tag: TagModel.objects.get_or_create(Title=tag)[0], tags)
    else:
        tag_list = []

    #계정확인   &  이미지 업로드
    if request.method == 'POST':
	entry.Title=edit_title
	entry.Content=edit_content
	entry.Category=edit_category
        form = ImageUploadForm(request.POST, request.FILES)
        if form.is_valid():
	    edit_image=request.FILES['image']
	    entry.Image=edit_image
    
    #꼬리표 임시추가 
    try:
        entry.save()
    except:
        return HttpResponse('Error: incomplete save for tag')
    
    # 꼬리표 추가
    entry.Tags=tag_list

    # 최종 저장.
    if len(tag_list) > 0:
        try:
            entry.save()
	    return redirect('/');
        except:
            return HttpResponse('Error: incomeplete saving')
    return HttpResponse('Error:nothiung happened')

def login_user(request):
    logout(request)
    username = password = ''
    state = 'Please login to write a post on Mini-reddit'
    if request.POST:
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username=username, password=password)
        if user is not None:
            if user.is_active:
                login(request, user)
                return HttpResponseRedirect('/')
	    else:
		state = 'Use user with admin control'
	else:
	    state = 'Invaild Password or Username. Please try it again.'
    context = {'username': username, 'state': state}
    return render(request,'login.html', context)

def logout_user(request):
    logout(request)
    return redirect('/')

def sign_up(request):
    return render(request, 'signup_form.html')

def add_user(request):
    # 글쓴이 이름 처리
    if request.POST.has_key('username') == False:
        return HttpResponse('Missing name')
    else:
	username = request.POST['username']
        if len(username) == 0:
            return HttpResponse('username must be exist')
	elif User.objects.filter(username=username).exists():
	    return HttpResponse('someone is using this uesrname')
        else:
            user_username = username

    # 비밀번호
    user_password = request.POST['inputPassword']

    # Email
    email=request.POST['email']
    if len(email) == 0:
            return HttpResponse('Email must be longer than one letter')
    elif User.objects.filter(email=email).exists():
	    return HttpResponse('someone is using email') 
    else:
            user_email = email

    # 글쓴이 이름 처리
    user_first_name = request.POST['first_name']

    # 글쓴이 이름 처리
    user_last_name = request.POST['last_name']
    
    try:
        user = User.objects.create_user(username=user_username, email=user_email, password=user_password)
	user.first_name=user_first_name
	user.last_name=user_last_name
	user.save()
	return redirect('/')
	#return HttpResponse(new_user)
    except:
        return HttpResponse('Error: couldnt create user')
    return HttpResponse('Err`or: End of the program. Didnt happened anything')    

def status(request):
    status=''
    if request.user.is_authenticated():
	status = 'Log Out'
    return status

def index(request, page=1):

    per_page = 10
    start_pos = (page - 1) * per_page
    end_pos = start_pos + per_page
    
    page_title = '블로그 글 목록 화면'
    
    entries = Entries.objects.select_related().all().order_by('-created')[start_pos:end_pos]

    context={
        'page_title':page_title,
        'entries':entries,
        'current_page':page,
    }
    return render(request, 'list.html', context)

def read(request, entry_id=None):
    page_title = '블로그 글 읽기 화면'
    
    try:
        current_entry = Entries.objects.get(id=int(entry_id))
    except:
        return HttpResponse('Post does not exist anymore')

    try:
        prev_entry = current_entry.get_previous_by_created()
    except:
        prev_entry = None
    
    try:
        next_entry = current_entry.get_next_by_created()
    except:
        next_entry = None

    comments = Comments.objects.filter(Entry=current_entry).order_by('created')
    
    context={
        'page_title':page_title,
        'current_entry':current_entry,
        'prev_entry':prev_entry,
        'next_entry':next_entry,
        'comments':comments
    }
    return render(request, 'read.html', context)

@login_required(login_url = '/login/')
def write_form(request):
    page_title = '블로그 글 쓰기 화면'
    
    categories = Categories.objects.all()
    context={
        'page_title':page_title,
        'categories':categories
    }
    return render(request, 'write_form.html', context)



def add_post(request):
    
    # 글 제목 처리
    if request.POST.has_key('title') == False:
        return HttpResponse('Missing title of the post')
    else:
        if len(request.POST['title']) == 0:
            return HttpResponse('Title must be longer than one letter')
        else:
            entry_title = request.POST['title']

    # 글 본문 처리
    if request.POST.has_key('content') == False:
        return HttpResponse('Missing content of the post')
    else:
        if len(request.POST['content']) == 0:
            return HttpResponse('Content must be longer than one letter')
        else:
            entry_content = request.POST['content']

    # 글 갈래 처리
    if request.POST.has_key('category') == False:
        return HttpResponse('Must choose category')
    else:
        try:
            entry_category = Categories.objects.get(id=request.POST['category'])
        except:
            return HttpResponse('Invaild category')

    # 글 꼬리표 처리    
    if request.POST.has_key('tags') == True:
        tags = map(lambda str: str.strip(), unicode(request.POST['tags']).split(','))
        tag_list = map(lambda tag: TagModel.objects.get_or_create(Title=tag)[0], tags)
    else:
        tag_list = []

    #계정확인   &  이미지 업로드
    if request.method == 'POST':
        form = ImageUploadForm(request.POST, request.FILES)
        if form.is_valid():
	    entry_user = request.user
            entry_image=request.FILES['image']
	    new_entry = Entries(User = entry_user, Title=entry_title, Content=entry_content, Category=entry_category, Image=entry_image)
    	else:
	    entry_user = request.user
            new_entry = Entries(User = entry_user, Title=entry_title, Content=entry_content, Category=entry_category)
    
    #꼬리표 임시추가 
    try:
        new_entry.save()
    except:
        return HttpResponse('Error: incomplete save for tag')
    
    # 꼬리표 추가
    for tag in tag_list:
        new_entry.Tags.add(tag)
        
    # 최종 저장.
    if len(tag_list) > 0:
        try:
            new_entry.save()
        except:
            return HttpResponse('Error: incomeplete saving')
    return redirect('/')
    #return HttpResponse(' Successfully saved post number %s' % new_entry.id)



def add_comment(request):    
    # 댓글 본문 처리
    if request.POST.has_key('content') == False:
        return HttpResponse('Missing content')
    else:
        if len(request.POST['content']) == 0:
            return HttpResponse('Content must be longer than one letter')
        else:
            cmt_content = request.POST['content']

    # 댓글 달 글 확인
    if request.POST.has_key('entry_id') == False:
        return HttpResponse('Missing targat to comment')
    else:
        try:
            entry = Entries.objects.get(id=request.POST['entry_id'])
        except:
            return HttpResponse('Post does not exsit anymore')

    try:
        new_cmt = Comments( User=request.user, Content=cmt_content, Entry=entry)
        new_cmt.save()
        entry.Comments += 1
        entry.save()
	return redirect('/entry/%s' %request.POST['entry_id'])
	#return HttpResponse('Successfully added comment')
    except:
        return HttpResponse('Error: while adding comment to server')
    return HttpResponse('Err`or: End of the program. Didnt happened anything')

def get_comments(request, entry_id=None, is_inner=False):    
    try:
        current_entry = Entries.objects.get(id=int(entry_id))
    except:
        return HttpResponse('그런 글이 존재하지 않습니다.')
        
    comments = Comments.objects.filter(Entry=current_entry).order_by('created')

    if is_ajax(request):
        with_layout = False
    else:        
        with_layout = True
    
    context={
    	'current_entry':current_entry,
        'comments':comments,
        'with_layout':with_layout
    }

blog/templates/comment_form.html
{% if user.is_authenticated%}
<div class="well">
    <h4>Leave a Comment:</h4>
    <form method="post" action="/add/comment/"> {% csrf_token %}
        <input type="hidden" name="entry_id" value="{{current_entry.id}}" />
        <!-- Comment Content -->
        <div class="form-group">
            <textarea id="content" name="content" class="form-control" rows="3"></textarea>
        </div>
        <button type="submit" class="btn btn-primary">Comment</button>
    </form>
</div>
{% else %}
	<h4><strong> Login to leave a Comment </strong></h4> 
{% endif %}

blog/templates/comments.html
{% load staticfiles %}
<h3> Comments </h3> 

<!-- Comments in for loop-->    
{% if comments|length %}
<ul class="list-group">
    {% for comment in comments %}
    <li class="list-group-item">
        <div class="comment-body">
            <h4 class="comment-heading"><a href="#">{{comment.User.username}}</a>
            <small>{{comment.created}}</small>
            </h4> 
            {{comment.Content}}
        </div>
    </li>
    {% endfor %} 
</ul>

<!-- No Comments-->    
{% else %}  
<li class="list-group-item">
    <div class="comment-body">
        <h4 class="comment-heading">
             No comments. 
        </h4> 
    </div>
</li>
{% endif %}

blog/templates/comments_only.html
{% extends "main.html" %}
{% block content %}
{% load staticfiles %}


<div class="container">
<h3> Comments </h3> 
<!-- Comments in for loop-->  
{% if comments|length %}
<ul class="list-group">
    {% for comment in comments %}
    <li class="list-group-item">
        <div class="comment-body">
            <h4 class="comment-heading"><a href="#">{{comment.User.username}}</a>
            <small>{{comment.created}}</small>
            </h4> 
            {{comment.Content}}
        </div>
    </li>
    {% endfor %} 
</ul>

<!-- No Comments-->    
{% else %}  
<li class="list-group-item">
    <div class="comment-body">
        <h4 class="comment-heading">
             No comments. 
        </h4> 
    </div>
</li>
</div>
{% endif %}
{% endblock %}

blog/templates/delete_post_form.html
{% extends "main.html" %}
{% block content %}
{% load staticfiles %}
<div class="container">
    <div class="row">
        <div class="col-md-offset-2 col-md-8" style="padding-top:5%;text-align: center;">
            <div class="well">
<form method="POST">{% csrf_token %}
    <h4><b>Are you sure you want to delete "{{ object.Title }}" ?</b></h4>
        <div class="form-group" style="padding-top:5%;">
            <button type="submit" class="btn btn-primary">Submit</button>
        </div>
</form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

blog/templates/list.html
{% extends "main.html" %}
{% block content %}
{% load staticfiles %}

<div class="container">
	<!-- Entry in for loop-->  
    {% for entry in entries %}
    <div class="post post-green">
        <strong><a href="/entry/{{entry.id}}"> {{entry.Title}} </strong></a> by <a href="">{{entry.User}} </a>
	<div class="pull-right">
		<!-- Delete Post -->
		{% if entry.User == request.user %}
		<a href="update/post/{{entry.id}}" class="glyphicon glyphicon-pencil"></a>
		<a href="delete/post/{{entry.id}}" class="glyphicon glyphicon-trash"></a>
		{% endif %}
	</div>
		<!-- Created Date-->  
        <div>Created: {{entry.created}}</div>
		<!-- Number of comments-->  
        <div>
        	<a href="/get_comments/{{entry.id}}">{{entry.Comments}} comments</a>
        </div>
    </div>
    {% endfor %}
</div>
{% endblock %}

blog/templates/login.html
{% load staticfiles %}
<!DOCTYPE>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="Mini reddit by using Django">
    <meta name="author" content="James W. Lee">
    <link rel="icon" href="../../favicon.ico">
    <title>Mini-Reddit</title>
    <!-- Bootstrap core CSS -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/style.css' %}" type="text/css" />
</head>

<body>
    <div class="container">
        <div class="row">
            <div class="col-md-offset-3 col-md-6">
                <form class="form-signin" name="LoginForm" action="/login/" method="post">
                    {% csrf_token %}
                    <h2 class="form-signin-heading">{{state}}</h2>
                    <!-- Input Username -->  
                    <div>
                        <label for="inputUsername" class="sr-only">Username</label>
                        <input type="username" name="username" id="username" class="form-control" placeholder="Username" required>
                        <p class="help-block"></p>
                    </div>
                    <!-- Input Password -->  
                    <div>
                        <label for="inputPassword" class="sr-only">Password</label>
                        <input type="password" name="password" id="password" class="form-control" placeholder="Password" required>
                        <p class="help-block"></p>
                    </div>
                    <!-- Link to reset password -->  
                    <div>
                     	<p class="text-left"><a href="/reset/password_form/">Forgot password?</a></p>
                    </div>
                    <!-- Check box to remeber -->  
                    <div>
                        <label>
                            <input type="checkbox" value="remember-me"> Remember me
                        </label>
                    </div>

                    <button class="btn btn-lg btn-primary btn-block" type="submit">Sign in</button>
                </form>
            </div>
        </div>
    </div>
</body>
</html>

blog/templates/main.html
<!DOCTYPE>
{% load staticfiles %}
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="Mini reddit by using Django">
    <meta name="author" content="James W. Lee">
    <link rel="icon" href="../../favicon.ico">
    <title>Mini-Reddit</title>
    <!-- Bootstrap core CSS -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/style.css' %}" type="text/css" />
</head>

<body>
    <nav class="navbar navbar-inverse">
            <!-- Navber -->  
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="/">Mini-Reddit</a>
            </div>
            <div id="navbar" class="collapse navbar-collapse">
                <ul class="nav navbar-nav">
                    <li><a href="/write">Write</a></li>
                </ul>
                <ul id="nav-right" class="nav navbar-nav navbar-right">
                    <!-- user is login, so show logout button -->  
                    {% if user.is_authenticated%}
                    <li class="navbar-right">
                        <a href="/logout/">Welcome, {{user.username}} | Log Out</a>
                    </li>
                    
                    {% else %}
                    <!-- user is not login, so show login form -->  
                    <form  method="post" action="/login/" class="navbar-form navbar-left" role="form">
                        {% csrf_token %}
                        <div class="input-group">
                            <span class="input-group-addon"><i class="glyphicon glyphicon-user"></i></span>
                            <input class="form-control" id="username" name="username" placeholder="Username" required>
                        </div>
                        <div class="input-group">
                            <span class="input-group-addon"><i class="glyphicon glyphicon-lock"></i></span>
                            <input class="form-control" type="password" name="password" id="password" placeholder="Password" required>
                        </div>
                        <button type="submit" class="btn btn-primary">Login</button>
                    </form>
                    <!-- user is not login, so show signup form -->  
                    <li>
                        <p class="navbar-btn">
                            <a href="/sign_up/" class="btn btn-default">Sign Up</a>
                        </p>
                    </li>
                    {% endif %}
                </ul>
        </div>
    </nav>
    {% block content%} 
    {% endblock %}
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js">
    </script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/validator.js' %}"></script>
    <script src="{% static 'js/validator.min.js' %}"></script>
</body>

</html>

blog/templates/read.html
{% extends "main.html" %}
{% block content%}
{% load staticfiles %}
<!-- Page Content -->
<div class="container">
    <div class="row">
        <!-- Mini Reddit Post Content Column -->
        <div class="col-md-offset-1 col-md-10">
            <!-- Mini Reddit Post -->
            <!-- Title -->
	    <div class ="pull-right">
		<!-- Delete Post -->
		{% if current_entry.User == request.user %}
		<a href="/update/post/{{current_entry.id}}" class="glyphicon glyphicon-pencil"></a>
		<a href="/delete/post/{{current_entry.id}}" class="glyphicon glyphicon-trash"></a>
		{% endif %}
	    </div>
            <h1>{{current_entry.Title}}</h1>
            <!-- Author -->
            <div class=" lead">
                by <a href="#">{{current_entry.User}}</a>
            </div>
            <hr>
            <!-- Mini Reddit created Date -->
            <p><span class="glyphicon glyphicon-time"></span> Posted on {{current_entry.created}}</p>
            <hr>
            <!-- Preview Image -->
            {% if not current_entry.Image == '' %}
            <img class="img-responsive" src="{{MEDIA_URL}}{{current_entry.Image}}" alt=""> 
            {% endif %}
            <!-- Mini Reddit Content -->
            <p>{{current_entry.Content}}</p>
            <hr>
            <p><strong>Category:</strong> {{current_entry.Category}}</p>
            <p><strong>Tag :</strong> {% for tag in current_entry.Tags.all %} {{tag.Title}} {% endfor %}</p>

            <!-- Comments -->
            <hr>
            <div>
                {% include 'comments.html' %}
                <hr>
                {% include 'comment_form.html' %}
            </div>
            <hr>
            <!-- Previous & Next post -->
            <ul>
                {% if prev_entry %}
                <li>
                    <a href="/entry/{{prev_entry.id}}">Previous Post({{prev_entry.Title}})</a>
                </li>
                {% endif %}
                {% if next_entry %}
                <li>
                    <a href="/entry/{{next_entry.id}}">Next Post({{next_entry.Title}})</a>
                </li>
                {% endif %}
            </ul>
        </div>
    </div>
</div>
{% endblock %}

blog/templates/update_post_form.html
{% extends "main.html" %}
{% block content%}
{% load staticfiles %}
<div class="container">
    <div class="row">
        <div class="col-md-offset-2 col-md-8">
            <form method="post" action='/update/post/complete/' enctype="multipart/form-data">
                <input type='hidden' name='entry_id' value={{current_entry.id}} />
                <input type='hidden' name='csrfmiddlewaretoken' value='EDtIhdX7j4I8S1FzQ6GbUErmhlasSISb' />
                <div>
                    <legend>Post at mini-reddit</legend>
                </div>
                {% csrf_token %}
                <!-- Input Title required-->  
                <div class="control-group">
                    <div class="controls">
                        <label class="control-label">Title</label>
                        <input type="text" name="title" class="form-control" placeholder="Title" value="{{current_entry.Title}}" id="title" required data-validation-required-message="Please enter title" />
                        <p class="help-block"></p>
                    </div>
                </div>
                <!-- Input Tags -->  
                <div class="control-group">
                    <div class="controls">
                        <label class="control-label">Tag</label>
                        <input type="tags" name="tags" class="form-control" placeholder="Tag" value="{% for tag in current_entry.Tags.all %}{{tag.Title}},{% endfor %}" id="tags"/>
                        <p class="help-block">Split tags by using space ex)tag1 tag2 tag3</p>
                    </div>
                </div>
                <!-- Input Category required-->  
                <div class="control">
                    <div class="form-group">
                        <label class="control-label">Category{{current_category}}</label>
                        <select class="form-control" name="category" id="cateogry">
                            {% for category in categories %}
				{% if current_entry.Category.Title == category.Title %}
                            		<option value="{{category.id}}" selected>{{category.Title}}</option>
				{% else %}
                            		<option value="{{category.id}}">{{category.Title}}</option>
				{% endif %}
                            {% endfor %}
                        </select>
                    </div>
                </div>
		
                <!-- Input Content required-->  
                <div class="control-group">
                    <div class="controls">
                        <label class="control-label">Content</label>
                        <textarea id="content" name="content" rows="10" cols="100" class="form-control" placeholder="Message" id="message" required data-validation-required-message="Please enter your message" minlength="5" data-validation-minlength-message="Min 5 characters" maxlength="999" style="resize:none">{{current_entry.Content}}</textarea>
                        <p class="help-block"></p>
                    </div>
                </div>
                <!-- Input Image -->  
                <p>
                    <input id="id_image" type="file" class="" name="image">
                </p>

                <!-- For success/fail messages -->
                <div id="success"> </div>
                <button type="submit" class="btn btn-primary pull-right">Post</button>
                <br/>
            </form>
        </div>
    </div>
</div>
{% endblock %}

blog/templates/write_form.html
{% extends "main.html" %}
{% block content%}
{% load staticfiles %}
<div class="container">
    <div class="row">
        <div class="col-md-offset-2 col-md-8">
            <form method="post" action='/add/post/' enctype="multipart/form-data">
                <input type='hidden' name='csrfmiddlewaretoken' value='EDtIhdX7j4I8S1FzQ6GbUErmhlasSISb' />
                <div>
                    <legend>Post at mini-reddit</legend>
                </div>
                {% csrf_token %}
                <!-- Input Title required-->  
                <div class="control-group">
                    <div class="controls">
                        <label class="control-label">Title</label>
                        <input type="text" name="title" class="form-control" placeholder="Title" id="title" required data-validation-required-message="Please enter title" />
                        <p class="help-block"></p>
                    </div>
                </div>
                <!-- Input Tags -->  
                <div class="control-group">
                    <div class="controls">
                        <label class="control-label">Tag</label>
                        <input type="tags" name="tags" class="form-control" placeholder="Tag" id="tags" required data-validation-required-message="Please enter your tag" />
                        <p class="help-block"></p>
                    </div>
                </div>
                <!-- Input Category required-->  
                <div class="control">
                    <div class="form-group">
                        <label class="control-label">Category</label>
                        <select class="form-control" name="category" id="cateogry">
                            {% for category in categories %}
                            <option value="{{category.id}}">{{category.Title}}</option>
                            {% endfor %}
                        </select>
                    </div>
                </div>
                <!-- Input Content required-->  
                <div class="control-group">
                    <div class="controls">
                        <label class="control-label">Content</label>
                        <textarea id="content" name="content" rows="10" cols="100" class="form-control" placeholder="Message" id="message" required data-validation-required-message="Please enter your message" minlength="5" data-validation-minlength-message="Min 5 characters" maxlength="999" style="resize:none"></textarea>
                        <p class="help-block"></p>
                    </div>
                </div>
                <!-- Input Image -->  
                <p>
                    <input id="id_image" type="file" class="" name="image">
                </p>

                <!-- For success/fail messages -->
                <div id="success"> </div>
                <button type="submit" class="btn btn-primary pull-right">Post</button>
                <br/>
            </form>
        </div>
    </div>
</div>
{% endblock %}